version: "3"

services:
  app:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    container_name: python_client


  redis:
    image: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli"]
      interval: 5s
      timeout: 5s
      retries: 5
